"""Generate notebooks/credit_scoring_analysis.ipynb from the project modules.

The notebook is a *narrative* walkthrough for the viva: it re-runs the light
steps (load, clean, EDA, feature engineering, split, fast model comparison) and
loads the heavy artefacts produced by ``python -m src.train`` instead of
retraining them, so it opens and runs in a couple of minutes.

    python -m scripts.build_notebook          # write the notebook
    python -m scripts.build_notebook --run    # write, then execute to verify
"""
from __future__ import annotations

import argparse
from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "notebooks" / "credit_scoring_analysis.ipynb"

CELLS: list[tuple[str, str]] = [
    ("md", """# Credit Scoring Model — Predicting Creditworthiness

**Task 1 — Machine Learning Internship**

**Problem.** Given an individual's past financial behaviour, predict whether they
are creditworthy. Formally: a **binary classification** problem where
`default = 1` means the customer failed to pay their next credit-card bill.

**Dataset.** UCI *Default of Credit Card Clients* (Taiwan, 2005) — 30,000 real
credit-card customers with six months of billing, payment and delinquency
history.

**Why classification?** The outcome is a discrete yes/no label, and lenders need
a *probability* of default to set a lending cut-off — exactly what a probabilistic
classifier provides.

> This notebook reproduces the analysis. The heavy hyper-parameter search lives in
> `src/train.py`; run `python -m src.train` first, then this notebook loads those
> results."""),

    ("code", """import sys, json, warnings
from pathlib import Path

# Make the project importable when the notebook runs from notebooks/
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import Image, display

from src import config
pd.set_option("display.width", 160)
pd.set_option("display.max_columns", 60)
print("Project root:", ROOT)
print("Random seed :", config.RANDOM_STATE)"""),

    ("md", """## 1. Data acquisition and cleaning

`src/data_loader.py` downloads the official UCI archive (cached locally), then applies
four cleaning decisions:

1. **Drop `ID`** — a row identifier carries no signal and would act as a leakage-style shortcut.
2. **Rename** the verbose target to `default`.
3. **Drop 35 exact duplicates** so the same customer cannot appear in both train and test.
4. **Recode `SEX` / `EDUCATION` / `MARRIAGE`** to readable labels, folding *undocumented*
   codes (EDUCATION 0/5/6, MARRIAGE 0) into `others`."""),

    ("code", """from src.data_loader import load_clean

df = load_clean()
print("Shape:", df.shape)
df.head()"""),

    ("md", "## 2. Data understanding\n\nShape, types, missingness, duplicates, and the target distribution."),

    ("code", """print("Rows, columns :", df.shape)
print("Missing values:", int(df.isna().sum().sum()))
print("Duplicate rows:", int(df.duplicated().sum()))
print()
print("Data types:")
print(df.dtypes.value_counts().to_string())
print()
counts = df[config.TARGET].value_counts().sort_index()
print("Target distribution:")
print(counts.to_string())
print(f"Default rate    : {df[config.TARGET].mean():.2%}")
print(f"Imbalance ratio : {counts[0] / counts[1]:.2f} : 1")"""),

    ("code", """# Numerical summary of the key financial columns
df[["LIMIT_BAL", "AGE", "BILL_AMT1", "PAY_AMT1", "PAY_0"]].describe().round(1)"""),

    ("code", """# Categorical summary
for col in ["SEX", "EDUCATION", "MARRIAGE"]:
    print(f"--- {col} ---")
    print(df[col].value_counts().to_string())
    print()"""),

    ("md", """### Columns that must NOT be used

| Column | Why it is excluded |
|---|---|
| `ID` | Pure row identifier. No causal link to default; a tree could memorise it. Dropped in cleaning. |
| `default` | The target itself — excluded from `X` by construction. |

**Leakage audit.** The target is default in **October 2005**; every predictor
describes **April–September 2005**. All features therefore precede the outcome
in time, so there is no look-ahead leakage. `PAY_0` (September status) is the
most recent signal but is legitimately known before the October bill."""),

    ("md", """## 3. Exploratory Data Analysis

Five figures, each answering a question that changes a modelling decision.
They are generated by `src/eda.py`."""),

    ("code", """from src import eda

paths = eda.run_all(df)
for p in paths:
    display(Image(filename=p))"""),

    ("md", """**What the EDA tells us**

1. **Target distribution** — 22.1% default. A model predicting "nobody defaults"
   already scores ~78% accuracy, so **accuracy alone is a misleading metric**.
2. **Payment history** — the default rate climbs steeply with `PAY_0` and with the
   number of late months. This is the dominant signal and motivates the engineered
   delinquency features.
3. **Financial profile** — defaulters cluster at *lower credit limits* and *higher
   utilisation*; age separates the classes poorly.
4. **Categoricals** — education and marital status shift the default rate modestly,
   so they are worth one-hot encoding.
5. **Correlation** — the six `BILL_AMT` columns are almost collinear (r > 0.9), which
   is why ratio features (utilisation) carry more information than raw balances."""),

    ("md", """## 4. Feature engineering

Every feature is computed **row-wise from a single customer's own record**, so this
step is leakage-free and may run before the split. Statistics that *are* learned from
data (imputation medians, scaler means, one-hot categories) live inside the sklearn
Pipeline instead.

| Group | Features | Financial meaning |
|---|---|---|
| Utilisation | `util_1..6`, `avg_utilization`, `max_utilization`, `utilization_trend`, `over_limit_months` | Share of the granted limit consumed. Sustained high utilisation signals stress. |
| Repayment effort | `pay_ratio_1..5`, `avg_pay_ratio`, `min_pay_ratio`, `zero_payment_months` | How much of last month's bill was actually paid off. |
| Delinquency | `n_delinquent_months`, `max_delinquency`, `recent_delinquency`, `delinquency_trend`, `months_paid_full`, `months_no_consumption` | Frequency, severity and *direction* of late payments. |
| Burden | `avg_bill_amt`, `avg_pay_amt`, `bill_volatility`, `payment_to_limit`, `remaining_credit` | Absolute debt load and capacity to service it. |

**Timing detail that matters:** `PAY_AMT_t` is the money paid *during* month *t*, which
settles the bill raised in month *t+1*. So `pay_ratio_t = PAY_AMT_t / BILL_AMT_{t+1}`."""),

    ("code", """from src.feature_engineering import (
    add_financial_features, engineered_feature_names, get_feature_lists,
)

feat = add_financial_features(df)
numeric, categorical = get_feature_lists()

print(f"Before : {df.shape[1] - 1} predictors")
print(f"After  : {len(numeric)} numeric + {len(categorical)} categorical "
      f"= {len(numeric) + len(categorical)} predictors")
print(f"Created: {len(engineered_feature_names())} new features")

feat[["LIMIT_BAL", "avg_utilization", "n_delinquent_months",
      "avg_pay_ratio", "delinquency_trend", config.TARGET]].head()"""),

    ("code", """# NaNs appear only where a ratio is genuinely undefined (no bill to repay).
# They are imputed INSIDE the pipeline, per fold - never globally.
nan_counts = feat[numeric].isna().sum()
nan_counts[nan_counts > 0].to_frame("missing")"""),

    ("code", """# Do the engineered features actually separate the classes?
key = ["avg_utilization", "n_delinquent_months", "avg_pay_ratio",
       "max_delinquency", "payment_to_limit"]
feat.groupby(config.TARGET)[key].mean().round(3).T.rename(
    columns={0: "repaid", 1: "defaulted"})"""),

    ("md", """## 5. Train / validation / test strategy

* **Train (80%)** — model fitting *and* all hyper-parameter search.
* **Validation** — 5-fold **stratified** cross-validation *inside* the training set.
  Stratification keeps the 22% default rate in every fold.
* **Test (20%)** — touched exactly once, for the final report. Never used for tuning
  or for choosing the decision threshold.

This is why the reported test scores are an honest estimate of new-customer performance."""),

    ("code", """from sklearn.model_selection import train_test_split

X = feat[numeric + categorical]
y = feat[config.TARGET]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=config.TEST_SIZE, stratify=y, random_state=config.RANDOM_STATE,
)
print(f"Train: {len(X_train):,} rows | default rate {y_train.mean():.4f}")
print(f"Test : {len(X_test):,} rows | default rate {y_test.mean():.4f}")
print("Index overlap:", len(set(X_train.index) & set(X_test.index)))"""),

    ("md", """## 6. Preprocessing pipeline

`ColumnTransformer` inside a `Pipeline`, so every statistic is learned per fold:

* **Numeric** → median imputation → standard scaling *(scaling only for Logistic
  Regression; tree ensembles are invariant to monotone rescaling)*
* **Categorical** → most-frequent imputation → one-hot encoding with
  `handle_unknown="ignore"` so an unseen category cannot crash scoring."""),

    ("code", """from src.preprocessing import build_preprocessor

pre = build_preprocessor(numeric, categorical, scale=True)
Xt = pre.fit_transform(X_train)
print("Transformed training matrix:", Xt.shape)
print("Any NaN left? ", bool(np.isnan(Xt).any()))
print("First 8 output columns:", list(pre.get_feature_names_out())[:8])"""),

    ("md", """## 7. Baseline and model comparison (cross-validated)

The **baseline** always predicts the majority class. It is the number every real model
must beat — and it exposes the accuracy trap: ~78% accuracy while catching *zero*
defaulters.

Below is a fast 3-fold comparison for the notebook. `src/train.py` runs the full
5-fold version plus the hyper-parameter search."""),

    ("code", """from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.metrics import make_scorer, precision_score, recall_score, f1_score
from src.models import build_models

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=config.RANDOM_STATE)
scoring = {
    "accuracy": "accuracy",
    "precision": make_scorer(precision_score, zero_division=0),
    "recall": make_scorer(recall_score, zero_division=0),
    "f1": make_scorer(f1_score, zero_division=0),
    "roc_auc": "roc_auc",
}

rows = {}
for name, pipe in build_models(numeric, categorical, balanced=True).items():
    res = cross_validate(pipe, X_train, y_train, cv=cv, scoring=scoring, n_jobs=1)
    rows[name] = {m.capitalize(): res[f"test_{m}"].mean() for m in scoring}

quick_cv = pd.DataFrame(rows).T.rename(columns={"Roc_auc": "ROC-AUC"})
quick_cv.round(4).sort_values("ROC-AUC", ascending=False)"""),

    ("md", """## 8. Full results from `src/train.py`

Everything below is loaded from disk — produced by executed code, never typed by hand."""),

    ("code", """cv_table = pd.read_csv(config.RESULTS_DIR / "cv_comparison.csv", index_col=0)
print("5-fold cross-validated comparison (training set only)")
cv_table.round(4)"""),

    ("code", """imb = pd.read_csv(config.RESULTS_DIR / "imbalance_study.csv")
print("Class-imbalance mitigation: class_weight='balanced' vs none")
imb.round(4)"""),

    ("md", """**Reading the imbalance study.** Re-weighting the minority class trades precision
for a large gain in **recall** — it makes the model far more willing to flag a risky
borrower. Because a missed defaulter costs a lender much more than a wrongly declined
applicant, that trade is the right one here.

*Why not SMOTE?* SMOTE would add the `imbalanced-learn` dependency and must be applied
**inside** each CV fold (never before the split) to avoid leaking synthetic neighbours
into validation. At a 3.5:1 ratio, `class_weight` achieves the same re-balancing with
no synthetic data and no extra dependency."""),

    ("code", """tune = pd.read_csv(config.RESULTS_DIR / "tuning_results.csv")
print("Hyper-parameter search results")
tune"""),

    ("code", """test_table = pd.read_csv(config.RESULTS_DIR / "test_comparison.csv", index_col=0)
print("FINAL COMPARISON — held-out test set")
test_table.round(4)"""),

    ("code", """for fig in ["model_comparison.png", "confusion_matrices.png",
            "roc_curves.png", "precision_recall_curves.png"]:
    display(Image(filename=str(config.FIGURES_DIR / fig)))"""),

    ("md", """## 9. Choosing the metric — the credit-risk argument

| Outcome | Meaning for the lender | Cost |
|---|---|---|
| **False Negative** — predicted repay, actually defaulted | A bad loan was **approved**. The bank loses the outstanding principal. | **High** |
| **False Positive** — predicted default, actually repaid | A good customer was **declined**. The bank loses the profit margin and some goodwill. | Lower |

* **Precision** = of the applicants we flagged as risky, how many really defaulted?
  Higher precision → fewer good customers wrongly rejected.
* **Recall** = of all the customers who actually defaulted, how many did we catch?
  Higher recall → fewer bad loans slipping through.
* **F1** = harmonic mean, used when both matter.
* **ROC-AUC** = probability the model ranks a random defaulter above a random payer.
  Threshold-independent, which makes it the right criterion for *choosing a model*.

**Conclusion.** We select the model on **ROC-AUC** (ranking quality), then tune the
**decision threshold** to favour **recall**, because a false negative is the expensive
error. We assume FN costs 5× FP and minimise total cost on out-of-fold predictions."""),

    ("code", """display(Image(filename=str(config.FIGURES_DIR / "threshold_analysis.png")))

summary = json.loads((config.RESULTS_DIR / "final_model_summary.json").read_text())
print(f"Selected model     : {summary['model_name']}")
print(f"Best parameters    : {summary['best_params']}")
print(f"CV ROC-AUC         : {summary['cv_roc_auc']:.4f}")
print(f"Decision threshold : {summary['threshold']:.3f}  "
      f"(cost model: FN={summary['cost_fn']:.0f}x, FP={summary['cost_fp']:.0f}x)")
print()
print("Test metrics at the tuned threshold:")
for k, v in summary["test_metrics_at_threshold"].items():
    print(f"  {k:<10} {v:.4f}")"""),

    ("md", """## 10. Interpretability — what drives credit risk?

Permutation importance measures the real drop in test ROC-AUC when a column is shuffled.
It is model-agnostic and, unlike impurity importance, is not biased toward
high-cardinality features."""),

    ("code", """display(Image(filename=str(config.FIGURES_DIR / "feature_importance_permutation.png")))

# Only tree/linear models expose a built-in importance attribute.
native = config.FIGURES_DIR / "feature_importance_native.png"
if native.exists():
    display(Image(filename=str(native)))
else:
    print("Selected model has no built-in importance attribute "
          "- permutation importance above is the reference measure.")

imp = pd.read_csv(config.RESULTS_DIR / "feature_importance.csv")
perm = imp[imp["type"] == "permutation_roc_auc_drop"].nlargest(12, "importance")
perm[["feature", "importance", "std"]].round(5).reset_index(drop=True)"""),

    ("md", """## 11. Error analysis

Where does the model go wrong, and is it wrong *confidently* or *narrowly*?"""),

    ("code", """err = pd.read_csv(config.RESULTS_DIR / "error_analysis.csv")
err.round(3)"""),

    ("md", """## 12. Prediction system — scoring a brand-new applicant

The saved bundle contains the **entire** pipeline (imputation → scaling → encoding →
classifier) plus the tuned threshold, so raw applicant data can be scored directly.
Every number below comes from the trained model at run time."""),

    ("code", """from src.predict import (
    load_model, predict_applicant, predict_batch, example_applicants, format_report,
)

bundle = load_model()
print(f"Model      : {bundle['model_name']}")
print(f"Trained at : {bundle['trained_at']}")
print(f"Threshold  : {bundle['threshold']:.3f}\\n")

for title, applicant in example_applicants().items():
    print(format_report(predict_applicant(applicant, bundle), title))
    print()"""),

    ("code", """# Batch scoring: score the first 10 real test customers and compare to truth
raw_cols = bundle["raw_input_columns"]
sample = df.loc[X_test.index[:10], raw_cols]
scored = predict_batch(sample, bundle)
scored["actual_outcome"] = np.where(
    y_test.loc[sample.index] == 1, "defaulted", "repaid")
scored"""),

    ("md", """## 13. Conclusions, limitations and next steps

**What predicts credit risk here?** Recent and repeated **payment delinquency**
(`PAY_0`, `n_delinquent_months`, `max_delinquency`) dominates, followed by
**repayment effort** (how much of the bill is actually paid) and **credit utilisation**.
Demographics contribute very little.

**Limitations**

1. **One market, one period** — Taiwanese credit-card holders in 2005. Behaviour and
   macroeconomic conditions differ elsewhere and today; the model needs revalidation
   before any other use.
2. **Six-month window** — no information on income, employment, other lenders, or
   longer credit history, all of which real bureaus use.
3. **Card default only** — predicts a missed *credit-card* payment, not bankruptcy or
   mortgage default.
4. **Assumed cost ratio** — the 5:1 FN:FP ratio is a modelling assumption; a real lender
   would use its own loss-given-default figures.
5. **Fairness** — `SEX`, `EDUCATION` and `MARRIAGE` are protected or proxy attributes and
   using them in lending is restricted in many jurisdictions. `outputs/results/fairness_sensitivity.csv`
   records how much predictive power is lost when `SEX` is dropped.
6. **Selection bias** — the data contains only *approved* applicants, so it cannot
   describe people who were already declined.

**Next steps:** calibration curves, monotonic constraints for regulatory
explainability, scorecard (WOE/IV) conversion, and monitoring for population drift."""),
]


def build() -> Path:
    nb = nbf.v4.new_notebook()
    nb.cells = [
        nbf.v4.new_markdown_cell(src) if kind == "md" else nbf.v4.new_code_cell(src)
        for kind, src in CELLS
    ]
    nb.metadata.update({
        "kernelspec": {"display_name": "Python 3", "language": "python",
                       "name": "python3"},
        "language_info": {"name": "python"},
    })
    NOTEBOOK.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, NOTEBOOK)
    return NOTEBOOK


def run() -> None:
    """Execute the notebook in place so we know every cell really works."""
    from nbclient import NotebookClient

    nb = nbf.read(NOTEBOOK, as_version=4)
    client = NotebookClient(
        nb, timeout=1800, kernel_name="python3",
        resources={"metadata": {"path": str(NOTEBOOK.parent)}},
    )
    client.execute()
    nbf.write(nb, NOTEBOOK)
    print(f"Executed {len(nb.cells)} cells without error.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", action="store_true",
                        help="execute the notebook after writing it")
    args = parser.parse_args()
    path = build()
    print("Wrote", path)
    if args.run:
        run()
